{% set name = "napari" %}
{% set version = "0.2.2" %}
{% set sha256 = "0e4a20f20be5db9224383e090d64718fb42c5359cdd8ee8be5c01076b7df230d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - napari=napari.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - backcall >=0.1.0
    - dask >=2.1.0
    - fsspec >=0.3.3
    - imageio >=2.5.0
    - ipykernel ==5.1.1
    - ipython >=7.7.0
    - numpy >=1.10.0
    - numpydoc >=0.9.1
    - pyopengl >=3.1.0
    - pyside2 >=5.12.3
    - qtconsole >=4.5.1
    - qtpy >=1.7.0
    - scikit-image >=0.15.0
    - scipy >=1.2.0
    - vispy >=0.6.1
    - wrapt >=1.11.1
    - zarr >=2.3.0

test:
  imports:
    - benchmarks
    - napari
    - napari._qt
    - napari._qt.layers
    - napari._qt.tests
    - napari._vispy
    - napari.components
    - napari.layers
    - napari.layers.base
    - napari.layers.image
    - napari.layers.image.tests
    - napari.layers.labels
    - napari.layers.points
    - napari.layers.shapes
    - napari.layers.shapes.shape_models
    - napari.layers.surface
    - napari.layers.vectors
    - napari.resources
    - napari.resources.icons
    - napari.util
    - napari.util.colormaps
    - napari.util.colormaps.vendored
    - napari.util.list
    - napari.util.tests
  commands:
    - napari --help

about:
  home: https://napari.org
  license: BSD License
  license_family: BSD
  license_file: LICENSE
  summary: n-dimensional array viewer in Python.
  doc_url: https://napari.org
  dev_url: https://github.com/napari/napari
