{% set name = "napari" %}
{% set version = "0.3.4" %}
{% set sha256 = "23c0a0dde1337726e1913b674fc181c5f00381276fc706137879d7ad1bd86d89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - backcall
    - cachey
    - dask
    - fsspec
    - imageio
    - ipykernel
    - ipython
    - jupyter_client
    - napari-plugin-engine
    - napari-svg
    - numpy
    - numpydoc
    - pluggy
    # - PyOpenGl
    # - PySide2
    - pyqt >=5.9
    - qtconsole
    - qtpy
    - scikit-image
    - scipy
    - tifffile
    - vispy >=0.6.4
    - wrapt
    - zarr

test:
  requires:
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pytest-ordering
    - pytest-timeout
    - zarr
  imports:
    - napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari
